### ISSUE TITLE
Trouble Displaying Iota Price

### ISSUE THREAD

**Issue by Faolain** [lacicloud/payiota-woocommerce#1] opened 2017-11-11 21:34 UTC
First I have to say great work on this plugin! I have a question as to how the application should show the appropriate amount of iota the customer should send. Currently the plugin/app simply says 0 iota and I was wondering where this quantity is coming from? Is there an exchange rate somewhere/api that it pulls from? 

<img width="255" alt="screen shot 2017-11-11 at 4 16 37 pm" src="https://user-images.githubusercontent.com/9613083/32693733-b7abe9b4-c6fd-11e7-8689-ee9ed097a0aa.png">

![23514944_3913235673309_1851772240_o](https://user-images.githubusercontent.com/9613083/32693757-16db75da-c6fe-11e7-9515-176145c41e3a.png)

**Comment by lacicloud** [comment] 2017-11-12 22:00
Hey!

This issue happens in version 1.0.6 only, because there is a variable misnaming error I had made. Can you try version 1.0.7 and verify that it no longer happens? Our server gets the price from CoinMarketCap's API.

**Comment by Faolain** [comment] 2017-11-13 03:31
Hey @lacicloud thanks for the quick response! I tried 1.0.7 and still am experiencing the same issue :/ I deactivated and deleted the previous plugin. Is there anything else I should do?

**Comment by lacicloud** [comment] 2017-11-13 06:46
@Faolain Can you download a plugin such as WP-Debug, enable error display, and send me a screenshot of the 0 MIOTA page?

**Comment by lacicloud** [comment] 2017-11-15 18:31
@Faolain Any update on this?

**Comment by Faolain** [comment] 2017-11-17 05:22
Hey @lacicloud sorry for the delay, I tried installing a few different debugging plugins (did not find WP-Debug specifically) but upon looking at the logs I didn't see anything in particular

[17-Nov-2017 05:16:20 UTC] PHP Notice:  Array to string conversion in /mnt/data/home/9232.cloudwaysapps.com/jqsdfsgdts/public_html/wp-includes/formatting.php on line 1031
[17-Nov-2017 05:16:28 UTC] PHP Notice:  Trying to get property of non-object in /mnt/data/home/9232.cloudwaysapps.com/jqsdfsgdts/public_html/wp-content/themes/labomba/includes/theme-actions.php on line 1985
[17-Nov-2017 05:16:46 UTC] PHP Notice:  Trying to get property of non-object in /mnt/data/home/9232.cloudwaysapps.com/jqsdfsgdts/public_html/wp-content/themes/labomba/includes/theme-actions.php on line 1985
[17-Nov-2017 05:16:51 UTC] PHP Notice:  Trying to get property of non-object in /mnt/data/home/9232.cloudwaysapps.com/jqsdfsgdts/public_html/wp-content/themes/labomba/includes/theme-actions.php on line 1985
[17-Nov-2017 05:17:01 UTC] PHP Notice:  Trying to get property of non-object in /mnt/data/home/9232.cloudwaysapps.com/jqsdfsgdts/public_html/wp-content/themes/labomba/includes/theme-actions.php on line 1985
[17-Nov-2017 05:17:04 UTC] PHP Notice:  Trying to get property of non-object in /mnt/data/home/9232.cloudwaysapps.com/jqsdfsgdts/public_html/wp-content/themes/labomba/includes/theme-actions.php on line 1985
[17-Nov-2017 05:17:08 UTC] PHP Notice:  Trying to get property of non-object in /mnt/data/home/9232.cloudwaysapps.com/jqsdfsgdts/public_html/wp-content/themes/labomba/includes/theme-actions.php on line 1985
[17-Nov-2017 05:17:12 UTC] PHP Notice:  Trying to get property of non-object in /mnt/data/home/9232.cloudwaysapps.com/jqsdfsgdts/public_html/wp-content/themes/labomba/includes/theme-actions.php on line 1985
[17-Nov-2017 05:17:17 UTC] PHP Notice:  Trying to get property of non-object in /mnt/data/home/9232.cloudwaysapps.com/jqsdfsgdts/public_html/wp-content/themes/labomba/includes/theme-actions.php on line 1985

wherein labomba is simply a wordpress theme.

**Comment by lacicloud** [comment] 2017-11-17 06:04
Ok. I'm not sure what the problem is. Is it fine for you to create a new WP admin account for me to debug the problem and send the credentials to support@payiota.me ?

**Comment by lacicloud** [comment] 2017-11-23 22:01
Hi @Faolain !

Have you got any update on this? Also, can you confirm just to be sure, that you are indeed using the website payiota.me and not paywithiota.com (paywithiota.com is a completely different, but similar service that has a different Github account) ? I do not see an email corresponding to your name or your website in my database.

**Comment by lacicloud** [comment] 2017-11-24 22:45
Closing due to lack of information. Please provide more information and I will re-open the issue.

**Closed as completed by lacicloud** 2017-11-24 22:45 UTC

**Comment by Faolain** [comment] 2017-12-03 18:25
Sorry for the delay @lacicloud as I was on holiday. I just used the new plugin and it all works fine :) thank you so much for your support. An additional unrelated question, is payiota.me currently down? I made a test purchase(on the woocommerce page) but it seems like payiota.me is unresponsive since I did so. Could the two be related?

**Comment by lacicloud** [comment] 2017-12-03 18:58
@Faolain that is great news and no problem! Hope you enjoyed your holiday. No, it is not down, but the IPN's have some delay, as usual. Maybe something wrong with your internet connection?

**Comment by Faolain** [comment] 2017-12-04 00:24
Hmm it loads now but I checked through a third party and it also said it was down at the time. Additionally if it helps at all the payiota main page provided an NGINX Timeout. Not sure if it was a coincidence or related to performing a purchase. It seems to work now though so maybe it was a momentary glitch.

**Comment by lacicloud** [comment] 2017-12-04 12:05
Ah well, hopefully it won't happen again. I think the server may have been under high load.
